numbers = list(range(0, 11))
print("The first three items in the list are : ")
print(numbers[:3])
print("The three items from the middle of the list are: ")
print(numbers[4:7])
print("The last three items in the list are: ")
print(numbers[8:])
