five_places = ["Tailand", "Japan", "Maldiv", "France", "India"]
print("Original : ", five_places)
print("Sorted : ", sorted(five_places))
print("Original : ", five_places)
print("Reversed : ", sorted(five_places, reverse=True))
print("Original : ", five_places)
five_places.reverse()
print("Reversed() : ", five_places)
print("Original : ", five_places)
five_places.reverse()
print("Reversed() : ", five_places)
print("Original : ", five_places)
five_places.sort()
print("Sort() : ", five_places)
five_places.sort(reverse=True)
print("Reverse() : ", five_places)
